# Run checks (tests, linting, etc.) on push

name: CI
on:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    working-directory: source

jobs:
  # Reference from: https://docs.cypress.io/guides/continuous-integration/github-actions#Install-Job
  # Goal is to only install the modules once
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache npm modules for later use
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      # installs the npm modules
      - name: Install modules
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # lint
      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Get node modules
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Install modules (cached)
        run: npm ci
        env:
          CYPRESS_CACHE_FOLDER: ~/.npm

      # run the test suite
      - name: Unit tests
        run: npm test

      # - name: Annotate tests on PR
      #   uses: mattallty/jest-github-action@v1.0.3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     working-directory: source
        
      - name: Run integration tests
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_CACHE_FOLDER: ~/.npm
        with:
          install: false
          working-directory: source
          browser: chrome
          start: npm start

      - name: Echo
        run: |
          ls -la
          ls -la ~
          ls -la ~/.npm