# Run checks (tests, linting, etc.) on push

name: CI
on:
  workflow_dispatch:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setups node with caching
      - name: Cache local node_modules
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ github.ref }}-
      
      - name: Cache Cypress installation
        uses: actions/cache@v3
        id: cache-cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
      
      # - name: Installation step
      #   uses: cypress-io/github-action@v2
      #   with:
      #     run-tests: false
      #   env:
      #     CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

      - name: Dependency installation
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3

      # Retrieves cached node_modules
      - name: Cache local node_modules
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ github.ref }}-

      # lint
      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3

      # Setups node with caching
      - name: Cache local node_modules
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ github.ref }}-
      
      - name: Cache Cypress installation
        uses: actions/cache@v3
        id: cache-cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}

      # # installs the npm modules
      # - name: Install modules
      #   run: npm --prefix source/ install

      # - name: Annotate tests on PR
      #   uses: mattallty/jest-github-action@v1.0.3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     test-command: "npm --prefix source/ test"

      # run the test suite
      - name: Run unit tests
        run: npm test
        
      - name: Run integration tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          start: npm start