# Run checks (tests, linting, etc.) on push

name: CI
on:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    working-directory: source

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # installs the npm modules
      - name: Install modules
        run: npm ci

      # lint
      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #installs the npm modules
      - name: Install modules
        run: npm ci

      # run the test suite
      - name: Run unit tests
        run: npm test

      - name: Annotate tests on PR
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm test"
        
      - name: Run integration tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: source
          browser: chrome
          start: npm start

